# Site settings
baseurl = "https://suryadhi.web.id/"
themesDir = "themes"
languageCode = "en-us"
title = "Suryablog - Life Journal as a Noob People"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-155095672-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "suryapersonalblog"

[params.adsense]
client = "ca-pub-5687102328508298"
inArticleSlot = "5687102328508298"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params.syntax]
use = "prismjs"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "dracula"
webFonts = true  # builtin: 'Source Code Pro'

[params]
	name = "Surya Adhi Kuncoro"
	description = "Surya Life Journal"
	bio = "Noob People"
	# Enter optionally your twitter account
	twitter = "suryadhikun"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "Noob People"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/suryadhikun"
    facebook = "https://web.facebook.com/suryadhikuncoro"
    instagram  = "https://www.instagram.com/suryadhikun/"
